### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by imasahiro** [goccy/gperl#7]
Hi!.

GPerl is missing a license.
Is it the same GPL license as libjit?

**Comment by goccy** [comment]
Oh....
Yes, I'm going to adopt GPL licence same as libjit.

**Comment by imasahiro** [comment]
I see.

Perl is also using the GPL license too. 
Would you be adapted for all the codes?

**Comment by goccy** [comment]
Yes, adapts all the codes.

**Comment by imasahiro** [comment]
OK. thx
